In [22]:
import numpy as np

In [23]:
X = np.matrix([[ 1, 1,-1,-1, 1, 1,-1,-1, 1, 1,-1,-1, 1, 1,-1,-1, 1, 1],
               [-1,-1,-1, 1, 1, 1,-1,-1,-1, 1, 1, 1,-1,-1,-1, 1, 1, 1],
               [-1,-1,-1,-1, 1, 1, 1, 1,-1,-1,-1,-1, 1, 1, 1, 1,-1,-1]])
print(X)

[[ 1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1]
 [-1 -1 -1  1  1  1 -1 -1 -1  1  1  1 -1 -1 -1  1  1  1]
 [-1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1  1  1 -1 -1]]


In [24]:
y = np.matrix([[ 1,-1, 1,-1],
               [ 1, 1,-1,-1],
               [-1,-1,-1,-1]])         
print(y)

[[ 1 -1  1 -1]
 [ 1  1 -1 -1]
 [-1 -1 -1 -1]]


In [25]:
w = X.T * y
print(w)

[[ 1 -1  3  1]
 [ 1 -1  3  1]
 [-1  1  1  3]
 [ 1  3 -1  1]
 [ 1 -1 -1 -3]
 [ 1 -1 -1 -3]
 [-3 -1 -1  1]
 [-3 -1 -1  1]
 [ 1 -1  3  1]
 [ 3  1  1 -1]
 [ 1  3 -1  1]
 [ 1  3 -1  1]
 [-1 -3  1 -1]
 [-1 -3  1 -1]
 [-3 -1 -1  1]
 [-1  1 -3 -1]
 [ 3  1  1 -1]
 [ 3  1  1 -1]]


In [60]:
def y_(X, w):
    y = np.dot(X, w)
    y[y <= 0] = -1
    y[y > 0] = 1
    return np.array(y)

In [61]:
def X_(y, w):
    X= np.dot(y, w.T)
    X[X <= 0] = -1
    X[X > 0] = 1
    return np.array(X)

In [70]:
def find_y(X, w):
    y_prev = y_(X, w)
    X_new = X_(y_prev, w)
    y = y_(X_new, w)
    while y_prev.any() != y.any():
        y_prev = y
        X_new = X_(y_prev, w)
        y = y_(X_new, w)
    return np.array(y)

In [77]:
def find_X(y, w):
    X_prev = X_(y, w)
    y_new = y_(X_prev, w)
    X = X_(y_new, w)
    while X_prev.any() != X.any():
        X_prev = X
        y_new = y_(X_prev, w)
        X = X_(y_new, w)
    return np.array(X)

In [80]:
print(f"{find_y(X[0], w)} -- {y[0]}")
print(f"{find_y(X[1], w)} -- {y[1]}")
print(f"{find_y(X[2], w)} -- {y[2]}")

[[ 1 -1  1 -1]] -- [[ 1 -1  1 -1]]
[[ 1  1 -1 -1]] -- [[ 1  1 -1 -1]]
[[-1 -1 -1 -1]] -- [[-1 -1 -1 -1]]


In [81]:
print(f"{find_X(y[0], w)} -- {X[0]}")
print(f"{find_X(y[1], w)} -- {X[1]}")
print(f"{find_X(y[2], w)} -- {X[2]}")

[[ 1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1]] -- [[ 1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1]]
[[-1 -1 -1  1  1  1 -1 -1 -1  1  1  1 -1 -1 -1  1  1  1]] -- [[-1 -1 -1  1  1  1 -1 -1 -1  1  1  1 -1 -1 -1  1  1  1]]
[[-1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1  1  1 -1 -1]] -- [[-1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1  1  1 -1 -1]]


In [82]:
print(f"{find_y([ 1,-1,-1,-1, 1, 1,-1,-1, 1, 1,-1,-1, 1, 1,-1,-1, 1, 1], w)} -- {y[0]}")
print(f"{find_y([-1, 1,-1, 1, 1, 1,-1,-1,-1, 1, 1, 1,-1,-1,-1, 1, 1, 1], w)} -- {y[1]}")
print(f"{find_y([-1, 1,-1,-1, 1, 1, 1, 1,-1,-1,-1,-1, 1, 1, 1, 1,-1,-1], w)} -- {y[2]}")

[[ 1 -1  1 -1]] -- [[ 1 -1  1 -1]]
[[ 1  1 -1 -1]] -- [[ 1  1 -1 -1]]
[[-1 -1 -1 -1]] -- [[-1 -1 -1 -1]]


In [84]:
print(f"{find_X([ 1, 1, 1,-1], w)} -- {X[0]}")
print(f"{find_X([ 1,-1,-1,-1], w)} -- {X[1]}")
print(f"{find_X([-1, 1,-1,-1], w)} -- {X[2]}")

[[ 1  1 -1  1  1  1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1]] -- [[ 1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1]]
[[-1 -1 -1 -1  1  1 -1 -1 -1  1 -1 -1  1  1 -1  1  1  1]] -- [[-1 -1 -1  1  1  1 -1 -1 -1  1  1  1 -1 -1 -1  1  1  1]]
[[-1 -1 -1  1  1  1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1]] -- [[-1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1  1  1 -1 -1]]


In [99]:
m = 4
L = m / (4 * np.log(m))
print()

print(np.log(np.exp(10)))

10.0
